version: "3"

tasks:
  default:
    cmds:
      - task: main
  main:
      cmds:
        - echo "***Running CLI***"
        - go run ./main.go  -v 
  mainv:
    cmds:
      - echo "***Running CLI***"
      - go run ./main.go  -v -rod="show,trace"
